//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataAccessPayments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameters
    {
        public System.Guid id_parameters { get; set; }
        public decimal maximum_transaction_amount { get; set; }
        public bool daily_gmf_calculation { get; set; }
    }
}
